# Generated by Django 4.2.4 on 2023-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='unknown@example.com', max_length=40)),
                ('password', models.CharField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student_details',
        ),
    ]
