# Generated by Django 4.2 on 2023-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_delete_student_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
