# Generated by Django 4.2 on 2023-08-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_student_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
